# DARIAH-DE status page
title: DARIAH-DE Status
timezone: Europe/Berlin
impressum_url: 'https://de.dariah.eu/Impressum'
support_mail: 'support@de.dariah.eu'

# Build settings
markdown: kramdown
#plugins:

collections:
  - services
  - middlewares
  - servers
  - infrastructure

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'index'

